### ISSUE TITLE
Move from Travis to GitHub actions

### ISSUE THREAD

**Issue by csdaw** [CambridgeCentreForProteomics/camprotR#16]
Unfortunately @TomSmithCGAT, after all your wrangling with Travis we'll need to move to GitHub actions as Travis may no longer be free to use (see [this blog post](https://deanattali.com/blog/migrating-travis-to-github/) amongst others).

Fortunately, this seems easy enough and there are simple instructions in that blog post. I'm happy to do this myself when I get the chance.

**Comment by TomSmithCGAT** [comment]
Can this be closed?

**Comment by csdaw** [comment]
I was going to close it when `{ts}_test_test_test` is merged with `master`.
