### ISSUE TITLE
Tests: to do

### ISSUE THREAD

**Issue by csdaw** [CambridgeCentreForProteomics/camprotR#19]
Ask about the following:
- [ ] What is the input to `get_parsimony_pep2prot()`?
- [x] How were the `.rds` files in `/data` generated?
- [ ] silac_psm_data is `data.frame` not `MSnSet`?

Do the following:
- [ ] Add some peptide level SILAC data in `/extdata` for testing `estimate_incorporation()`. Also need this for getting 100% test coverage on `parse_features()`.
- [x] Have a look at the `.rds` files in `/tests/testthat/`. Need to move them into their own folder to reduce clutter.
- [x] Make the names and internal structure of test files consistent.

Need help with the following:
- [x] Add a phospho PD output in `/inst/extdata` to test some of the functions in `ptm.R`.
- [ ] Understand what the functions in `/R/combine_runs.R` do and write tests for them.
- [x] Writing a test for `restrict_features_per_protein()`.

**Comment by TomSmithCGAT** [comment]
`get_parsimony_pep2prot` is a quick hacky way to make sure the peptide to protein assignments are the same when samples have been analysed in separate batches in PD. For TMT, it should be possible to combine experiments in a 'multiconsensus' PD workflow. For LFQ, there are times where one only wants MBR (or whatever the PD equivalent is called) to be used for groups of samples, hence separate sample batches for PD. This is the current use case for the function

The input is just a list of the PD outfiles. For the LFQ use case, I've just used peptide level output, though without checking, I believe the function would work fine from PSM level output too if desired.

The updated mapping from peptide to protein uses an approximate parsimony approach. Hence the function also compares the updated mapping to the peptide to protein matching from PD.

**Comment by TomSmithCGAT** [comment]
' silac_psm_data is data.frame not MSnSet?' - This is possibly just due to my inability to work out how best to deal with SILAC in an MSnSet. For SILAC data, I tend to keep the data in a data.frame initially and only convert to MSnSet post ratio calculation but this is probably not ideal. Might be worth checking the documentation to see if there are any recommendations/functions for encoding SILAC data in MSnSets. One could just add the labelling information to `pData` and expect their to be a column called e.g label for example. Would need to re-write functions for determining ratios etc but nothing difficult

**Comment by TomSmithCGAT** [comment]
' Understand what the functions in /R/combine_runs.R do and write tests for them.' - Let me know if there is a specific function(s) that needs a better explanation. Or is it all of them!

**Comment by TomSmithCGAT** [comment]
'Add some peptide level SILAC data' - From our conversation, I understand you have this in hand?

**Comment by csdaw** [comment]
`get_parsimony_pep2prot()` - thanks, the explanation is helpful
`silac_psm_data` - this makes sense. I can do a little digging into MSnSet at some point.
`combine_runs()` - I think I will have a handle on these once I've looked at them more closely.
Peptide level SILAC data - yep I've got some incorporation tests that I can use.
